-- Generated by matugen from ~/.config/quickshell/nothing/matugen/templates/hyprland.lua
hl.config({
    general = {
        col = {
            active_border   = "rgba({{colors.primary.default.hex_stripped}}bb)",
            inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}55)",
        },
    },
    misc = {
        background_color = "rgba({{colors.surface.default.hex_stripped}}ff)",
    },
})
