#!/usr/bin/env bash
# Writes ~/.config/hypr/hypridle.conf from config.json (idle.* in minutes,
# 0 = never) and restarts hypridle. Run by the Settings window.
set -uo pipefail
CFG="$(dirname "$0")/../config.json"
get() { jq -r "$1 // $2" "$CFG" 2>/dev/null || echo "$2"; }
LOCK=$(get .idle.lock 5); OFF=$(get .idle.screenOff 10); SUSP=$(get .idle.suspend 15)

{
cat <<'HEAD'
# Generated by ~/.config/quickshell/nothing/scripts/idle.sh (edit in Settings)
general {
    lock_cmd = qs -c nothing ipc call lock lock || (pidof hyprlock || hyprlock)
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    inhibit_sleep = 3
}
HEAD
(( LOCK > 0 )) && printf '\nlistener {\n    timeout = %d\n    on-timeout = loginctl lock-session\n}\n' $((LOCK * 60))
(( OFF > 0 )) && printf '\nlistener {\n    timeout = %d\n    on-timeout = hyprctl dispatch '"'"'hl.dsp.dpms({ action = "disable" })'"'"'\n    on-resume = hyprctl dispatch '"'"'hl.dsp.dpms({ action = "enable" })'"'"'\n}\n' $((OFF * 60))
(( SUSP > 0 )) && printf '\nlistener {\n    timeout = %d\n    on-timeout = systemctl suspend || loginctl suspend\n}\n' $((SUSP * 60))
} > "$HOME/.config/hypr/hypridle.conf"

pkill -x hypridle
setsid hypridle >/dev/null 2>&1 < /dev/null &
