#!/usr/bin/env python3
"""Kitty colours from the matugen palette.

Surfaces come straight from matugen; the 16 ANSI colours keep their
conventional hues (so `ls` red still means red) but are nudged toward the
wallpaper's primary hue and toned to sit on the generated background.
"""
import colorsys
import json
import sys

src, dst = sys.argv[1], sys.argv[2]
c = json.load(open(src))
dark = c.get("mode", "dark") != "light"


def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def hexc(r, g, b):
    return "#" + "".join(f"{round(max(0, min(1, v)) * 255):02x}" for v in (r, g, b))


primary_hue = colorsys.rgb_to_hls(*rgb(c["primary"]))[0] * 360


def harmonize(hue, amount=0.18):
    diff = (primary_hue - hue + 180) % 360 - 180
    return (hue + diff * amount) % 360


def ansi(hue, bright):
    light = (0.72 if bright else 0.64) if dark else (0.40 if bright else 0.34)
    sat = 0.55 if dark else 0.60
    return hexc(*colorsys.hls_to_rgb(harmonize(hue) / 360, light, sat))


hues = {1: 3, 2: 125, 3: 42, 4: 215, 5: 290, 6: 185}  # red green yellow blue magenta cyan
lines = {
    "background": c["surface"],
    "foreground": c["on_surface"],
    "cursor": c["primary"],
    "cursor_text_color": c["on_primary"],
    "selection_background": c["primary_container"],
    "selection_foreground": c["on_primary_container"],
    "url_color": c["primary"],
    "active_border_color": c["primary"],
    "inactive_border_color": c["outline_variant"],
    "color0": c["surface_container_high"],
    "color8": c["outline"],
    "color7": c["on_surface_variant"],
    "color15": c["on_surface"],
}
for i, hue in hues.items():
    lines[f"color{i}"] = ansi(hue, False)
    lines[f"color{i + 8}"] = ansi(hue, True)

with open(dst, "w") as f:
    f.write("# Generated by ~/.config/quickshell/nothing/scripts/kitty.py\n")
    for k, v in lines.items():
        f.write(f"{k} {v}\n")
