#!/usr/bin/env bash
# Applies the shared shape + cursor tokens (config.json look.*) outside the
# shell: Hyprland window rounding and gaps, the cursor, and the launcher.
# Writes ~/.config/hypr/hyprland/look.lua so it survives restarts.
set -uo pipefail
CFG="$(dirname "$0")/../config.json"
get() { jq -r "$1 // $2" "$CFG" 2>/dev/null || echo "$2"; }
R=$(get .look.radius 20); G=$(get .look.gap 8)
BRUTAL=$(get .look.brutal false)
[[ "$BRUTAL" == true ]] && R=0
LOCKROUND=-1; [[ "$BRUTAL" == true ]] && LOCKROUND=0
CUR=$(get .look.cursor '"Bibata-Modern-Classic"'); CS=$(get .look.cursorSize 24)
GI=$(( (G + 1) / 2 ))

cat > "$HOME/.config/hypr/hyprland/look.lua" <<LUA
-- Generated by ~/.config/quickshell/nothing/scripts/look.sh (Settings > Appearance > Shape).
-- One corner radius and one gap for everything: windows match the pill,
-- cards, launcher and lock screen; window-to-window = window-to-pill = edge gap.
hl.config({
    decoration = { rounding = $R },
    general = { gaps_in = $GI, gaps_out = $G },
})
hl.env("XCURSOR_THEME", "$CUR")
hl.env("XCURSOR_SIZE", "$CS")
LUA

if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
    hyprctl eval "hl.config({ decoration = { rounding = $R }, general = { gaps_in = $GI, gaps_out = $G } })" >/dev/null
    hyprctl setcursor "$CUR" "$CS" >/dev/null
fi
# Launcher: render the fuzzel template with the shared radius (never edit
# tracked files in place - they may be symlinks into the repo).
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/nothing"; mkdir -p "$STATE"
sed "s/@RADIUS@/$R/; s/@SELRADIUS@/$(( R * 7 / 10 ))/" "$(dirname "$0")/../apps/fuzzel/fuzzel.base.ini" > "$STATE/fuzzel.ini"
mkdir -p "$HOME/.config/hypr/hyprlock"
printf '# Generated by look.sh\n$rounding = %s\n' "$LOCKROUND" > "$HOME/.config/hypr/hyprlock/shape.conf"
