-- Hyprland, minimal. Part of Everything-dots (github.com/SambuddhaRoy/Everything-dots).
-- Shell: ~/.config/quickshell/nothing (qs -c nothing)
-- Files marked "generated" below are written by the shell and aren't in the repo.

local function optional(mod, file)
    if is_file_exists(HOME .. "/.config/hypr/" .. file) then
        require(mod)
    end
end

require("hyprland.lib")
require("hyprland.lib.bindlog") -- records binds for Nothing Settings

require("hyprland.env")
require("hyprland.execs")
require("hyprland.general")
require("hyprland.rules")
optional("hyprland.colors", "hyprland/colors.lua") -- generated: wallpaper colours
require("hyprland.keybinds")

-- Personal additions (kept from before)
for _, f in ipairs({ "env", "execs", "general", "rules", "keybinds" }) do
    if is_file_exists(HOME .. "/.config/hypr/custom/" .. f .. ".lua") then
        require("custom." .. f)
    end
end

-- Keybinds edited in Nothing Settings (generated from keybinds.json)
optional("hyprland.keybinds-custom", "hyprland/keybinds-custom.lua")

-- nwg-displays support
optional("workspaces", "workspaces.lua")
optional("monitors", "monitors.lua")

-- HyprMod managed settings (monitor, input), machine-specific
optional("hyprland-gui", "hyprland-gui.lua")

-- Shared radius / gap / cursor tokens (generated by the shell's look.sh)
optional("hyprland.look", "hyprland/look.lua")

-- Nothing Settings overrides (generated; wins over everything above)
optional("hyprland.settings", "hyprland/settings.lua")

-- Let Nothing Settings see every bind (~/.local/state/nothing/binds.json)
nothing_dump_binds()
